### ISSUE TITLE
problem with rails generate refills:list

### ISSUE THREAD

**Issue by heaversm** [thoughtbot/refills#240]
Running this command seems to generate information only on the `rails generate` command, not a list of refills snippets as documented. You can run `rails generate` and it has the same effect as running `rails generate refills:list`. Unless there is some sort of issue with my configuration?

**Comment by teoljungberg** [comment]
@heaversm - I `rails new`'d an application that includes refills

```
$ rails g refills:list
Available Refills
=================
- accordion-tabs-minimal
- accordion-tabs
- accordion
- animate-info
- animate
- badges
- breadcrumbs
- button-group
- cards
- centered-navigation
- comment
- device
- dropdown
- expander
- fade-in
- flashes
- flex-boxes
- footer-2
- footer
- grid-items-lines
- grid-items
- hero
- hover-tile-animation
- icon-bullet-points
- image-gradient-dynamic
- maps
- modal
- navigation
- pagination
- parallax
- progress-bar-indication
- progress-bar
- ribbon
- scroll-on-page
- search-bar
- search-tools
- side-image
- sliding-menu
- stats
- switch
- tables-minimal
- tables
- texture-legend
- textures
- tooltip
- type-system-geometric
- type-system-rounded
- type-system-sans
- type-system-serif
- type-system-slab
- type-system-traditional
- vertical-tabs
- video
```
This can be related, we just released `0.1.0` of refills. Could you try bumping the version in your application?
If that doesn't help, we need some more details to debug the issue more. Like what version of rails you are on etc.

**Comment by heaversm** [comment]
@teoljungberg  - I upgraded the gem (`bundle update refills`) but still experience the same thing. I'm on ruby 2.2.0p0 with bundler v 1.7.12.

**Comment by teoljungberg** [comment]
There is something on your side here, what version of rails are you on? Could anything be colliding? Can you reproduce the issue elsewhere? What are the minimal steps of reproducing the issue, if you can reproduce it?

**Comment by teoljungberg** [comment]
@heaversm I'll close this until we have more information to work from
